services:
  # auth-service:
  #   build:
  #     context: ./auth-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     NODE_ENV: production
  #     DATABASE_URL: ${DATABASE_URL}
  #     JWT_SECRET: ${JWT_SECRET}
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network
  user_service_db:
    image: postgres:15-alpine
    ports:
      - '5433:5432'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  user-data:
    driver: local

networks:
  app-network:
    driver: bridge
